#!/usr/bin/env node
// Compiles workflows/*.ncl into .github/workflows/*.lock.yml.
//
//   node compile.mjs          write the lock files
//   node compile.mjs --check  fail if a lock file is stale or
//                                         hand-edited, or if a source in
//                                         tests/reject/ compiles
//
// Uses `nickel` from PATH, or $NICKEL.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = import.meta.dirname;
const SOURCES = "workflows";
const REJECT = "tests/reject";
const OUT = ".github/workflows";
const NICKEL = process.env.NICKEL ?? "nickel";

function nickelExport(file) {
  const r = spawnSync(NICKEL, ["export", "--format", "yaml", file], { cwd: ROOT, encoding: "utf8" });
  if (r.error) throw new Error(`running ${NICKEL}: ${r.error.message}`);
  return { ok: r.status === 0, stdout: r.stdout, stderr: r.stderr };
}

function nclFiles(dir) {
  return readdirSync(path.join(ROOT, dir)).filter((f) => f.endsWith(".ncl")).sort().map((f) => path.join(dir, f));
}

const check = process.argv.includes("--check");
const problems = [];

for (const src of nclFiles(SOURCES)) {
  const lock = path.join(OUT, `${path.basename(src, ".ncl")}.lock.yml`);
  const r = nickelExport(src);
  if (!r.ok) {
    problems.push(`${src} does not compile:\n${r.stderr}`);
    continue;
  }
  const text = `# Generated by workflow-compiler from ${src}; do not edit.\n# Regenerate with: node compile.mjs\n${r.stdout}`;
  if (!check) {
    writeFileSync(path.join(ROOT, lock), text);
    console.log(`wrote ${lock}`);
  } else if (!existsSync(path.join(ROOT, lock)) || readFileSync(path.join(ROOT, lock), "utf8") !== text) {
    problems.push(`${lock} does not match ${src}; run node compile.mjs and commit the result`);
  }
}

if (check) {
  for (const src of nclFiles(REJECT)) {
    const expect = /^# expect: (.*)$/m.exec(readFileSync(path.join(ROOT, src), "utf8"))?.[1];
    const r = nickelExport(src);
    if (!expect) problems.push(`${src} has no "# expect:" line`);
    else if (r.ok) problems.push(`${src} compiled, but should fail with "${expect}"`);
    else if (!r.stderr.includes(expect)) problems.push(`${src} failed without "${expect}":\n${r.stderr}`);
    else console.log(`ok: ${src} rejected (${expect})`);
  }
}

for (const p of problems) console.error(`error: ${p}`);
process.exit(problems.length ? 1 : 0);
