//! The workflow compiler: evaluates the nickel workflow sources in
//! `workflows/` (which call `lib/gha.ncl`'s `compile`) in-process with
//! `nickel-lang-core`, and writes or checks their lock files in
//! `.github/workflows/`.

pub mod nickel;

use std::path::Path;

use anyhow::{Context, Result};

/// Where workflow sources live, relative to the repository root.
pub const SOURCES_DIR: &str = "workflows";
/// Where lock files go, relative to the repository root.
pub const LOCKS_DIR: &str = ".github/workflows";
/// Sources that must fail to compile, each with the message its
/// `# expect:` line names.
pub const REJECT_DIR: &str = "tests/reject";
/// How to regenerate what `compile` writes, from the repository root.
pub const REGENERATE: &str = "cargo run -- compile";
/// The prefix of a reject test's expected message.
const EXPECT: &str = "# expect: ";

/// What to do with the repository.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Write the lock files.
    Compile,
    /// Fail if anything `Compile` writes is stale, and run the tests.
    Check,
}

/// The lock file's header.
fn header(source: &str) -> String {
    format!(
        "# Generated by workflow-compiler from {source}; do not edit.\n# Regenerate with: {REGENERATE}\n"
    )
}

/// The lock file of `source` (`workflows/x.ncl`), relative to the root.
pub fn lock_path(source: &str) -> String {
    let stem = source
        .rsplit('/')
        .next()
        .unwrap_or(source)
        .trim_end_matches(".ncl");
    format!("{LOCKS_DIR}/{stem}.lock.yml")
}

/// The `.ncl` files in `root/dir`, relative to `root` and sorted; none if
/// it doesn't exist.
fn ncl_files(root: &Path, dir: &str) -> Result<Vec<String>> {
    let entries = match std::fs::read_dir(root.join(dir)) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(e).with_context(|| format!("reading {dir}")),
    };
    let mut files = Vec::new();
    for entry in entries {
        let name = entry.with_context(|| format!("reading {dir}"))?.file_name();
        if let Some(name) = name.to_str().filter(|n| n.ends_with(".ncl")) {
            files.push(format!("{dir}/{name}"));
        }
    }
    files.sort();
    Ok(files)
}

/// `root/rel`, or `None` if it doesn't exist.
fn read_optional(root: &Path, rel: &str) -> Result<Option<String>> {
    match std::fs::read_to_string(root.join(rel)) {
        Ok(text) => Ok(Some(text)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e).with_context(|| format!("reading {rel}")),
    }
}

/// Where two texts first differ: the 1-based line number and both lines.
pub fn first_difference(a: &str, b: &str) -> Option<(usize, String, String)> {
    let (mut la, mut lb) = (a.lines(), b.lines());
    for n in 1.. {
        match (la.next(), lb.next()) {
            (None, None) => return None,
            (x, y) if x == y => continue,
            (x, y) => {
                return Some((
                    n,
                    x.unwrap_or("(end)").to_owned(),
                    y.unwrap_or("(end)").to_owned(),
                ));
            }
        }
    }
    unreachable!()
}

/// A problem if `committed` (`path`, or `None` if it's missing) isn't
/// `compiled`, from `source`.
fn stale(path: &str, source: &str, committed: Option<&str>, compiled: &str) -> Option<String> {
    let Some(committed) = committed else {
        return Some(format!("{path} is missing; run `{REGENERATE}`"));
    };
    if committed == compiled {
        return None;
    }
    let (at, lines) = match first_difference(committed, compiled) {
        Some((line, want, got)) => (
            format!("from line {line}"),
            format!("\n  committed: {want}\n  compiled:  {got}"),
        ),
        None => (
            "in its line endings or final newline".to_owned(),
            String::new(),
        ),
    };
    Some(format!(
        "{path} does not match {source}, {at}; run `{REGENERATE}` and review the difference{lines}"
    ))
}

/// Compiles or checks the repository at `root`, returning the problems
/// found.
pub fn run(root: &Path, mode: Mode) -> Result<Vec<String>> {
    let root = root
        .canonicalize()
        .with_context(|| format!("resolving {}", root.display()))?;
    match mode {
        Mode::Check => check(&root),
        Mode::Compile => compile(&root),
    }
}

fn check(root: &Path) -> Result<Vec<String>> {
    let mut problems = Vec::new();
    let sources = ncl_files(root, SOURCES_DIR)?;
    for source in &sources {
        let path = lock_path(source);
        match nickel::export_yaml(root, source) {
            Err(e) => problems.push(format!("{e:#}")),
            Ok(yaml) => {
                let committed = read_optional(root, &path)?;
                problems.extend(stale(
                    &path,
                    source,
                    committed.as_deref(),
                    &(header(source) + &yaml),
                ));
            }
        }
    }
    let rejects = ncl_files(root, REJECT_DIR)?;
    for source in &rejects {
        let text = std::fs::read_to_string(root.join(source))
            .with_context(|| format!("reading {source}"))?;
        let Some(expect) = text.lines().find_map(|l| l.strip_prefix(EXPECT)) else {
            problems.push(format!("{source} has no \"{EXPECT}\" line"));
            continue;
        };
        match nickel::export_yaml(root, source) {
            Ok(_) => problems.push(format!(
                "{source} compiled, but should fail with \"{expect}\""
            )),
            Err(e) => {
                let report = format!("{e:#}");
                if !report.contains(expect) {
                    problems.push(format!("{source} failed without \"{expect}\":\n{report}"));
                }
            }
        }
    }
    eprintln!(
        "checked {} lock files and {} reject tests",
        sources.len(),
        rejects.len()
    );
    Ok(problems)
}

/// What one compile of every source found.
#[derive(Default)]
struct Pass {
    problems: Vec<String>,
    /// Files to write, relative to the root, with their contents.
    outputs: Vec<(String, String)>,
}

/// Compiles every source, writing nothing.
fn compile_pass(root: &Path) -> Result<Pass> {
    let mut pass = Pass::default();
    for source in ncl_files(root, SOURCES_DIR)? {
        match nickel::export_yaml(root, &source) {
            Ok(yaml) => pass
                .outputs
                .push((lock_path(&source), header(&source) + &yaml)),
            Err(e) => pass.problems.push(format!("{e:#}")),
        }
    }
    Ok(pass)
}

/// Writes each of `outputs` that changed.
fn write_outputs(root: &Path, outputs: &[(String, String)]) -> Result<()> {
    for (rel, text) in outputs {
        if read_optional(root, rel)?.as_deref() != Some(text.as_str()) {
            std::fs::write(root.join(rel), text).with_context(|| format!("writing {rel}"))?;
            eprintln!("wrote {rel}");
        }
    }
    Ok(())
}

fn compile(root: &Path) -> Result<Vec<String>> {
    let pass = compile_pass(root)?;
    write_outputs(root, &pass.outputs)?;
    Ok(pass.problems)
}
