//! The workflow compiler: evaluates the nickel workflow sources in
//! `workflows/` (which call `lib/gha.ncl`'s `compile`) in-process with
//! `nickel-lang-core`, and writes or checks their lock files in
//! `.github/workflows/`. Everything it reads and writes goes through the
//! repository's directory fd ([`repo`]).

pub mod actions;
pub mod nickel;
pub mod repo;

use std::collections::{BTreeMap, btree_map};
use std::path::Path;

use anyhow::{Result, bail};

use crate::repo::Repo;

/// Where workflow sources live, relative to the repository root.
pub const SOURCES_DIR: &str = "workflows";
/// Where lock files go, relative to the repository root.
pub const LOCKS_DIR: &str = ".github/workflows";
/// Sources that must fail to compile, each with the message its
/// `# expect:` line names.
pub const REJECT_DIR: &str = "tests/reject";
/// Sources that must compile, to what their .expected.yml next to them
/// says, which is how tests of the compiler's rewriting (composite
/// actions from tests/actions/, for one) check its output without making
/// a workflow of it.
pub const ACCEPT_DIR: &str = "tests/accept";
/// How to regenerate what `compile` writes, from the repository root.
pub const REGENERATE: &str = "cargo run -- compile";
/// The prefix of a reject test's expected message.
const EXPECT: &str = "# expect: ";
/// How many rounds of locking new actions a compile may take: each
/// round locks what the sources are missing, and a composite action can
/// pull in more.
const MAX_LOCK_ROUNDS: usize = 50;

/// What to do with the repository.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Write the lock files and expected outputs, locking new actions.
    Compile,
    /// Fail if anything `Compile` writes is stale, and run the tests.
    Check,
}

/// The lock file's header.
fn header(source: &str) -> String {
    format!(
        "# Generated by workflow-compiler from {source}; do not edit.\n# Regenerate with: {REGENERATE}\n"
    )
}

/// The lock file of `source` (`workflows/x.ncl`), relative to the root.
pub fn lock_path(source: &str) -> String {
    let stem = source
        .rsplit('/')
        .next()
        .unwrap_or(source)
        .trim_end_matches(".ncl");
    format!("{LOCKS_DIR}/{stem}.lock.yml")
}

/// The expected output of the accept test `source`.
fn expected_path(source: &str) -> String {
    format!("{}.expected.yml", source.trim_end_matches(".ncl"))
}

/// Where two texts first differ: the 1-based line number and both lines.
pub fn first_difference(a: &str, b: &str) -> Option<(usize, String, String)> {
    let (mut la, mut lb) = (a.lines(), b.lines());
    for n in 1.. {
        match (la.next(), lb.next()) {
            (None, None) => return None,
            (x, y) if x == y => continue,
            (x, y) => {
                return Some((
                    n,
                    x.unwrap_or("(end)").to_owned(),
                    y.unwrap_or("(end)").to_owned(),
                ));
            }
        }
    }
    unreachable!()
}

/// A problem if `committed` (`path`, or `None` if it's missing) isn't
/// `compiled`, from `source`.
fn stale(path: &str, source: &str, committed: Option<&str>, compiled: &str) -> Option<String> {
    let Some(committed) = committed else {
        return Some(format!("{path} is missing; run `{REGENERATE}`"));
    };
    if committed == compiled {
        return None;
    }
    let (at, lines) = match first_difference(committed, compiled) {
        Some((line, want, got)) => (
            format!("from line {line}"),
            format!("\n  committed: {want}\n  compiled:  {got}"),
        ),
        None => (
            "in its line endings or final newline".to_owned(),
            String::new(),
        ),
    };
    Some(format!(
        "{path} does not match {source}, {at}; run `{REGENERATE}` and review the difference{lines}"
    ))
}

/// Compiles or checks the repository at `root`, returning the problems
/// found. Only fetching new actions' metadata happens outside it.
pub fn run(root: &Path, mode: Mode) -> Result<Vec<String>> {
    let repo = Repo::open(root)?;
    match mode {
        Mode::Check => check(&repo),
        Mode::Compile => compile(&repo),
    }
}

fn check(root: &Repo) -> Result<Vec<String>> {
    let lock = actions::read_lock(root)?;
    let mut problems = actions::check_lock(root, &lock);
    let sources = root.list(SOURCES_DIR, ".ncl")?;
    for source in &sources {
        let path = lock_path(source);
        match nickel::export_yaml(root, source) {
            Err(e) => problems.push(format!("{e:#}")),
            Ok(yaml) => {
                let committed = root.read(&path)?;
                problems.extend(stale(
                    &path,
                    source,
                    committed.as_deref(),
                    &(header(source) + &yaml),
                ));
            }
        }
    }
    let accepts = root.list(ACCEPT_DIR, ".ncl")?;
    for source in &accepts {
        let path = expected_path(source);
        match nickel::export_yaml(root, source) {
            Err(e) => problems.push(format!("{e:#}")),
            Ok(yaml) => {
                let committed = root.read(&path)?;
                problems.extend(stale(&path, source, committed.as_deref(), &yaml));
            }
        }
    }
    let rejects = root.list(REJECT_DIR, ".ncl")?;
    for source in &rejects {
        let text = root.read(source)?.unwrap_or_default();
        let Some(expect) = text.lines().find_map(|l| l.strip_prefix(EXPECT)) else {
            problems.push(format!("{source} has no \"{EXPECT}\" line"));
            continue;
        };
        match nickel::export_yaml(root, source) {
            Ok(_) => problems.push(format!(
                "{source} compiled, but should fail with \"{expect}\""
            )),
            Err(e) => {
                let report = format!("{e:#}");
                if !report.contains(expect) {
                    problems.push(format!("{source} failed without \"{expect}\":\n{report}"));
                }
            }
        }
    }
    eprintln!(
        "checked {} lock files, {} accept tests, {} reject tests and {} locked actions",
        sources.len(),
        accepts.len(),
        rejects.len(),
        lock.len()
    );
    Ok(problems)
}

/// What one compile of every source found.
#[derive(Default)]
struct Pass {
    problems: Vec<String>,
    /// Files to write, relative to the root, with their contents.
    outputs: Vec<(String, String)>,
    /// Actions the sources use that aren't locked yet, with their entries
    /// if they are fixtures.
    missing: BTreeMap<String, Option<actions::Entry>>,
}

impl Pass {
    /// Records the failure `e` to compile `source`, unless it is only a
    /// missing action.
    fn failed(
        &mut self,
        root: &Repo,
        lock: &actions::Lock,
        source: &str,
        e: anyhow::Error,
        expected: bool,
    ) -> Result<()> {
        let report = format!("{e:#}");
        match actions::missing_action(&report) {
            Some(uses) if lock.contains_key(&uses) => {
                self.problems.push(format!(
                    "{source}: {uses} is locked, but gha.ncl can't find it:\n{report}"
                ));
            }
            Some(uses) => {
                if let btree_map::Entry::Vacant(missing) = self.missing.entry(uses) {
                    let fixture = actions::lock_fixture(root, missing.key())?;
                    missing.insert(fixture);
                }
            }
            None if expected => {}
            None => self.problems.push(report),
        }
        Ok(())
    }
}

/// Compiles every source, writing nothing.
fn compile_pass(root: &Repo) -> Result<Pass> {
    let lock = actions::read_lock(root)?;
    let mut pass = Pass::default();
    for (dir, is_accept) in [(SOURCES_DIR, false), (ACCEPT_DIR, true)] {
        for source in root.list(dir, ".ncl")? {
            match nickel::export_yaml(root, &source) {
                Ok(yaml) if is_accept => pass.outputs.push((expected_path(&source), yaml)),
                Ok(yaml) => pass
                    .outputs
                    .push((lock_path(&source), header(&source) + &yaml)),
                Err(e) => pass.failed(root, &lock, &source, e, false)?,
            }
        }
    }
    // Only to lock the actions they use; they must still fail to compile.
    for source in root.list(REJECT_DIR, ".ncl")? {
        if let Err(e) = nickel::export_yaml(root, &source) {
            pass.failed(root, &lock, &source, e, true)?;
        }
    }
    Ok(pass)
}

/// Writes each of `outputs` that changed.
fn write_outputs(root: &Repo, outputs: &[(String, String)]) -> Result<()> {
    for (rel, text) in outputs {
        if root.read(rel)?.as_deref() != Some(text.as_str()) {
            root.write(rel, text)?;
            eprintln!("wrote {rel}");
        }
    }
    Ok(())
}

fn compile(root: &Repo) -> Result<Vec<String>> {
    // Fixtures are relocked from tests/actions/ on every compile.
    let mut lock = actions::read_lock(root)?;
    let relocked = actions::relock_fixtures(root, &mut lock)?;
    if relocked {
        actions::write_lock(root, &lock)?;
    }
    for _ in 0..MAX_LOCK_ROUNDS {
        let pass = compile_pass(root)?;
        if pass.missing.is_empty() {
            write_outputs(root, &pass.outputs)?;
            return Ok(pass.problems);
        }
        for (uses, fixture) in pass.missing {
            let entry = match fixture {
                Some(entry) => entry,
                None => actions::fetch(&uses)?,
            };
            lock.insert(uses, entry);
        }
        actions::write_lock(root, &lock)?;
    }
    bail!("the sources still need new actions after {MAX_LOCK_ROUNDS} rounds of locking")
}
