//! The workflow compiler's front end: evaluates a nickel workflow source
//! (which calls `lib/gha.ncl`'s `compile`) in-process with
//! `nickel-lang-core`, and renders the lock file `compile.mjs` writes.

use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use landlock::{
    ABI, Access, AccessFs, Ruleset, RulesetAttr, RulesetCreatedAttr, RulesetStatus,
    path_beneath_rules,
};
use nickel_lang_core::error::report::{ColorOpt, report_as_str};
use nickel_lang_core::eval::cache::CacheImpl;
use nickel_lang_core::program::{Program, ProgramBuilder};
use nickel_lang_core::serialize::{self, ExportFormat};

/// Where workflow sources live, relative to the repository root.
pub const SOURCES_DIR: &str = "workflows";
/// Where lock files go, relative to the repository root.
pub const LOCKS_DIR: &str = ".github/workflows";
/// What a compile may read, relative to the repository root: the
/// compiler's library and runtime, which the lock files embed, the
/// sources, the tests, the actions' metadata, and the lock files `--check`
/// compares with. Not `.git`, nor anything else in the checkout.
pub const READABLE: &[&str] = &[
    "lib",
    "runtime",
    SOURCES_DIR,
    "tests",
    "actions.lock.json",
    LOCKS_DIR,
];

/// The lock file's header, as `compile.mjs` writes it.
fn header(source: &str) -> String {
    format!(
        "# Generated by workflow-compiler from {source}; do not edit.\n# Regenerate with: node compile.mjs\n"
    )
}

/// `root/rel` if it exists, refusing it if it's a symlink or resolves to
/// somewhere outside `root`: Landlock grants what a rule's path resolves
/// to, so a `runtime` symlinked to `.git` would grant `.git`.
fn grantable(root: &Path, rel: &Path) -> Result<Option<PathBuf>> {
    let path = root.join(rel);
    let Ok(meta) = std::fs::symlink_metadata(&path) else {
        return Ok(None);
    };
    if meta.file_type().is_symlink() {
        bail!(
            "{} is a symlink; refusing to let the compile read through it",
            rel.display()
        );
    }
    let real = path
        .canonicalize()
        .with_context(|| format!("resolving {}", path.display()))?;
    if !real.starts_with(root) {
        bail!(
            "{} resolves to {}, outside {}",
            rel.display(),
            real.display(),
            root.display()
        );
    }
    Ok(Some(real))
}

/// Confines this thread, and every thread it starts from now on, to
/// reading the [`READABLE`] paths under `root` that exist, and the files
/// `extra` (relative to `root`, such as a source outside those), with
/// Landlock. nickel resolves `import` against any path
/// (`/etc/passwd`, `../x`, a symlink out of the tree, `/dev/zero`), and a
/// source may come from a pull request, so without this compiling it
/// could put any file the process can read into the output or its errors.
/// Fails if the kernel can't enforce it.
pub fn confine_reads(root: &Path, extra: &[PathBuf]) -> Result<()> {
    let abi = ABI::V1;
    let mut paths = Vec::new();
    for rel in READABLE
        .iter()
        .map(PathBuf::from)
        .chain(extra.iter().cloned())
    {
        paths.extend(grantable(root, &rel)?);
    }
    // A file rule grants only that file, whatever the directory holds.
    if let Some(p) = paths
        .iter()
        .find(|p| p.is_dir() && extra.iter().any(|e| root.join(e) == **p))
    {
        bail!("{} is a directory, not a source", p.display());
    }
    let status = Ruleset::default()
        .handle_access(AccessFs::from_all(abi))?
        .create()?
        .add_rules(path_beneath_rules(&paths, AccessFs::from_read(abi)))?
        .restrict_self()
        .context("restricting reads to the repository with Landlock")?;
    if status.ruleset == RulesetStatus::NotEnforced {
        bail!(
            "this kernel doesn't enforce Landlock, so reads can't be confined to {}",
            root.display()
        );
    }
    Ok(())
}

/// `source` as the path relative to the root that compile.mjs names it by
/// (`./workflows/x.ncl` is `workflows/x.ncl`). Refuses `..` and absolute
/// paths.
pub fn normalize_source(source: &str) -> Result<String> {
    let mut parts = Vec::new();
    for c in Path::new(source).components() {
        match c {
            Component::CurDir => {}
            Component::Normal(p) => {
                parts.push(p.to_str().ok_or_else(|| anyhow!("{source} isn't UTF-8"))?)
            }
            _ => bail!("{source} must be a path inside the repository root, without `..`"),
        }
    }
    if parts.is_empty() {
        bail!("{source} names no file");
    }
    Ok(parts.join("/"))
}

/// Evaluates the nickel file at `root/source` and exports it as YAML, as
/// `nickel export --format yaml` does. Errors carry nickel's own report.
pub fn export_yaml(root: &Path, source: &str) -> Result<String> {
    let path: PathBuf = root.join(source);
    let mut program: Program<CacheImpl> = ProgramBuilder::new()
        .add_path(&path)
        .build()
        .with_context(|| format!("loading {}", path.display()))?;
    let value = match program.eval_full_for_export() {
        Ok(value) => value,
        Err(error) => {
            let report = report_as_str(&mut program.files(), error, ColorOpt::Never);
            return Err(anyhow!("{source} does not compile:\n{report}"));
        }
    };
    serialize::validate(ExportFormat::Yaml, &value)
        .and_then(|()| serialize::to_string(ExportFormat::Yaml, &value))
        .map_err(|error| {
            let error = error.with_pos_table(program.pos_table().clone());
            let report = report_as_str(&mut program.files(), error, ColorOpt::Never);
            anyhow!("{source} can't be exported as YAML:\n{report}")
        })
}

/// The lock file for `source` (relative to `root`, e.g.
/// `workflows/sandbox-test.ncl`), byte for byte what `compile.mjs` writes.
pub fn compile_lock(root: &Path, source: &str) -> Result<String> {
    Ok(header(source) + &export_yaml(root, source)?)
}

/// The path of `source`'s lock file, relative to the repository root.
pub fn lock_path(source: &str) -> Result<String> {
    let stem = Path::new(source)
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| anyhow!("{source} has no file name"))?;
    Ok(format!("{LOCKS_DIR}/{stem}.lock.yml"))
}

/// Where two texts first differ: the 1-based line number and both lines.
pub fn first_difference(a: &str, b: &str) -> Option<(usize, String, String)> {
    let (mut la, mut lb) = (a.lines(), b.lines());
    for n in 1.. {
        match (la.next(), lb.next()) {
            (None, None) => return None,
            (x, y) if x == y => continue,
            (x, y) => {
                return Some((
                    n,
                    x.unwrap_or("(end)").to_owned(),
                    y.unwrap_or("(end)").to_owned(),
                ));
            }
        }
    }
    unreachable!()
}
