# sandbox-test: Install a tool system-wide
# shellcheck shell=bash
sudo tee /usr/local/bin/hello-tool >/dev/null <<'EOF'
#!/bin/sh
echo "installed by runner_steps, run by $(id -un)"
EOF
sudo chmod 0755 /usr/local/bin/hello-tool
echo RUNNER-SECRET-MARKER >"$HOME/runner-secret.txt"
ln -s /etc/shadow shadow-link
ln -s /etc shadow-dir
mkdir generated
echo "generated by runner_steps" >generated/data.txt
echo "left behind by runner_steps" >untracked.txt
